### ISSUE TITLE
Please consider assigning version numbers

### ISSUE THREAD

**Issue by olebole** [basp-group/sopt#5]
Hi,

we are thinking of [packaging sopt for the Debian distribution](https://bugs.debian.org/832659). For this, it would help much, if you could assign a version number to the current release. This makes it easier for the user to reference to a specific release. And since sopt is unchanged since almost 3 years, the current status can be taken as quite stable

Thank you very much, 

best regards

Ole

**Comment by mdavezac** [comment]
We've added a tag for the latest release v2.0.0 and will be using standard version number from here on.
Thanks!

**Comment by mdavezac** [comment]
FYI, I still have not updated the build-system to avoid downloading stuff.
